services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "8081:8081"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Dhudson.util.ProcessTree.disable=true"

volumes:
  jenkins_home: