services:
  psoft-staging:
    image: psoft-g1:staging
    container_name: psoft-staging
    build:
      context: .
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    volumes:
      - ./data-staging:/app/data

  psoft-prod:
    image: psoft-g1:prod
    container_name: psoft-prod
    build:
      context: .
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./data-prod:/app/data