version: '3.8'

services:
  h2:
    image: oscarfonts/h2
    container_name: h2-${SPRING_PROFILE}
    ports:
      - "${DB_PORT:-1521}:1521"
      - "${H2_WEB_PORT:-81}:81"
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - ./h2-data-${SPRING_PROFILE}:/opt/h2-data

  app:
    build: .
    container_name: psoft-g1-${SPRING_PROFILE}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - h2
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
